
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Khofi Muffin
 */
public class kasir extends javax.swing.JFrame {

    /**
     * Creates new form kasir
     */
    public kasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        maem = new javax.swing.JTextField();
        mimik = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        maem3 = new javax.swing.JCheckBox();
        maem1 = new javax.swing.JCheckBox();
        maem2 = new javax.swing.JCheckBox();
        mimik3 = new javax.swing.JCheckBox();
        mimik1 = new javax.swing.JCheckBox();
        mimik2 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        s1 = new javax.swing.JRadioButton();
        s2 = new javax.swing.JRadioButton();
        tgl = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        show = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KHOFI  PIZZA");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(360, 10, 190, 37);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("serve you with smile");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 50, 170, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 90);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "YOUR ORDER TODAY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Makanan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Minuman");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Jumlah");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Jumlah");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Uang bayar");

        maem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maemActionPerformed(evt);
            }
        });

        mimik.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mimik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mimikActionPerformed(evt);
            }
        });

        bayar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        maem3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maem3.setText("Pizza Deluxe");

        maem1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maem1.setText("Pizza Today");

        maem2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maem2.setText("Cheesy Pizza");

        mimik3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mimik3.setText("Very Black Coffe");

        mimik1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mimik1.setText("Freezy Float");

        mimik2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mimik2.setText("Messy Ice");
        mimik2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mimik2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 0));
        jLabel12.setText("PROMO JIKA MEMESAN LEBIH DARI");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 0));
        jLabel13.setText("200K");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 0));
        jLabel14.setText("DAPAT DISKON");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 0, 0));
        jLabel15.setText("20%");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(maem1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(mimik1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(maem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(mimik, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(maem3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addComponent(mimik3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(maem2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addComponent(mimik2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maem1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mimik1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maem2)
                            .addComponent(mimik2))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maem3)
                            .addComponent(mimik3))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mimik, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14))
                            .addComponent(jLabel15))))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 160, 870, 180);

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Kasir");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Shift");

        nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buttonGroup1.add(s1);
        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.setText("Pagi");

        buttonGroup1.add(s2);
        s2.setForeground(new java.awt.Color(255, 255, 255));
        s2.setText("Malam");

        tgl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nama)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(s1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(s2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tgl)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 100, 870, 50);

        print.setBackground(new java.awt.Color(153, 0, 0));
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(30, 390, 830, 30);

        save.setBackground(new java.awt.Color(153, 0, 0));
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(30, 350, 160, 30);

        clear.setBackground(new java.awt.Color(153, 0, 0));
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(250, 350, 160, 30);

        show.setBackground(new java.awt.Color(153, 0, 0));
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show);
        show.setBounds(470, 350, 160, 30);

        del.setBackground(new java.awt.Color(153, 0, 0));
        del.setForeground(new java.awt.Color(255, 255, 255));
        del.setText("Delete");
        getContentPane().add(del);
        del.setBounds(700, 350, 160, 30);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TODAY SELL");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(390, 20, 112, 25);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 430, 900, 60);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "NamaKasir", "Shift", "Makanan", "JmlMakan ", "Minuman", "JmlMinum", "TotalHarga", "UangBayar", "UangKembalil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 490, 900, 200);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 900, 740);

        setBounds(0, 0, 910, 731);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        int jml_maem;
        int jml_mimik;
        int yar;
        jml_maem = Integer.parseInt(maem.getText());
        jml_mimik = Integer.parseInt(mimik.getText());
        yar = Integer.parseInt(bayar.getText());
        
        if ("".equals(nama.getText()) || "".equals(buttonGroup1)){
            JOptionPane.showMessageDialog(this, "Harap Datanya Dilengkapi ya Sayang :*", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
        
        String ES = "";
        if (s1.isSelected()){
            ES = "Pagi";
        } else {
            ES = "Malam";
        }
        
        String MAKAN = "";
        if ((maem1.isSelected() && maem2.isSelected()) && maem3.isSelected()){
            MAKAN = "Pizza Today, Cheesy Pizza, and Pizza Deluxe";
        } else if (maem1.isSelected() && maem2.isSelected()){
            MAKAN = "Pizza Today and Cheesy Pizza";
        } else if (maem1.isSelected() && maem3.isSelected()){
            MAKAN = "Pizza Today and Pizza Deluxe";
        } else if (maem2.isSelected() && maem3.isSelected()){
            MAKAN = "Cheesy Pizza and Pizza Deluxe";
        } else if (maem1.isSelected()){
            MAKAN = "Pizza Today";
        } else if (maem2.isSelected()){
            MAKAN = "Cheesy Pizza";
        } else {
            MAKAN = "Pizza Deluxe";
        }
        
         String MINUM = "";
        if ((mimik1.isSelected() && mimik2.isSelected()) && mimik3.isSelected()){
            MINUM = "Freezy Float, Messy Ice, and Very Black Coffe";
        } else if (mimik1.isSelected() && mimik2.isSelected()){
            MINUM = "Freezy Float and Messy Ice";
        } else if (mimik1.isSelected() && mimik3.isSelected()){
            MINUM = "Freezy Float and Very Black Coffe";
        } else if (mimik2.isSelected() && mimik3.isSelected()){
            MINUM = "Messy Ice and Very Black Coffe";
        } else if (mimik1.isSelected()){
            MINUM = "Freezy Float";
        } else if (mimik2.isSelected()){
            MINUM = "Messy Ice";
        } else if (mimik3.isSelected()){
            MINUM = "Very Black Coffe";
        }
        
        int TTL_MAKAN = 0;
        if((maem1.isSelected() && maem2.isSelected()) && maem3.isSelected()){
            TTL_MAKAN = (40000+50000+60000)*jml_maem;
        } else if(maem1.isSelected() && maem2.isSelected()){
            TTL_MAKAN = (40000+50000)*jml_maem;
        } else if(maem1.isSelected() && maem3.isSelected()){
            TTL_MAKAN = (40000+60000)*jml_maem;
        } else if(maem2.isSelected() && maem3.isSelected()){
            TTL_MAKAN = (50000+60000)*jml_maem;
        } else if(maem1.isSelected()){
            TTL_MAKAN = 40000*jml_maem;
        } else if(maem2.isSelected()){
            TTL_MAKAN = 50000*jml_maem;
        } else if(maem3.isSelected()){
            TTL_MAKAN = 60000*jml_maem;
        }
        int TTL_MINUM = 0;
        if((mimik1.isSelected() && mimik2.isSelected()) && mimik3.isSelected()){
            TTL_MINUM = (20000+15000+10000)*jml_mimik;
        } else if(mimik1.isSelected() && mimik2.isSelected()){
            TTL_MINUM = (20000+15000)*jml_mimik;
        } else if(mimik1.isSelected() && mimik3.isSelected()){
            TTL_MINUM = (20000+10000)*jml_mimik;
        } else if(mimik2.isSelected() && mimik3.isSelected()){
            TTL_MINUM = (15000+10000)*jml_mimik;
        } else if(mimik1.isSelected()){
            TTL_MINUM = 20000*jml_mimik;
        } else if(mimik2.isSelected()){
            TTL_MINUM = 15000*jml_mimik;
        } else if(mimik3.isSelected()){
            TTL_MINUM = 10000*jml_mimik;
        }
        
        int TTL_POKOK = TTL_MAKAN + TTL_MINUM;
        int bagi = TTL_POKOK*(2/10);
        int TOTAL = 0;
        if (TTL_POKOK > 200000){
            TOTAL = TTL_POKOK - bagi;
        } else {
            TOTAL = TTL_POKOK;
        }
        
        int KEMBALI = yar - TTL_MAKAN;
        
        String SQL = "INSERT INTO penjualan "
                    + "VALUES('"+tgl.getText()+"','"+nama.getText()+"','"+ES+"','"
                    +MAKAN+"','"+jml_maem+"','"+MINUM+"','"
                    +jml_mimik+"','"+TOTAL+"','"+yar+"','"+KEMBALI+"')";
        int status = KoneksiDB.execute(SQL);
        if (status == 1){
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            selectData();
        } else {JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
                
            }
        }
        
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        maem.setText("");
        mimik.setText("");
        bayar.setText("");
        buttonGroup1.clearSelection();
        maem1.setSelected(false);
        maem2.setSelected(false);
        maem3.setSelected(false);
        mimik1.setSelected(false);
        mimik2.setSelected(false);
        mimik3.setSelected(false);
    }//GEN-LAST:event_clearActionPerformed

    private void mimik2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mimik2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mimik2ActionPerformed

    private void mimikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mimikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mimikActionPerformed

    private void maemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maemActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        int jml_maem;
        int jml_mimik;
        int yar;
        jml_maem = Integer.parseInt(maem.getText());
        jml_mimik = Integer.parseInt(mimik.getText());
        yar = Integer.parseInt(bayar.getText());
        
        String MAKAN = "";
        if ((maem1.isSelected() && maem2.isSelected()) && maem3.isSelected()){
            MAKAN = "Pizza Today, Cheesy Pizza, and Pizza Deluxe";
        } else if (maem1.isSelected() && maem2.isSelected()){
            MAKAN = "Pizza Today and Cheesy Pizza";
        } else if (maem1.isSelected() && maem3.isSelected()){
            MAKAN = "Pizza Today and Pizza Deluxe";
        } else if (maem2.isSelected() && maem3.isSelected()){
            MAKAN = "Cheesy Pizza and Pizza Deluxe";
        } else if (maem1.isSelected()){
            MAKAN = "Pizza Today";
        } else if (maem2.isSelected()){
            MAKAN = "Cheesy Pizza";
        } else {
            MAKAN = "Pizza Deluxe";
        }
        
        String MINUM = "";
        if ((mimik1.isSelected() && mimik2.isSelected()) && mimik3.isSelected()){
            MINUM = "Freezy Float, Messy Ice, and Very Black Coffe";
        } else if (mimik1.isSelected() && mimik2.isSelected()){
            MINUM = "Freezy Float and Messy Ice";
        } else if (mimik1.isSelected() && mimik3.isSelected()){
            MINUM = "Freezy Float and Very Black Coffe";
        } else if (mimik2.isSelected() && mimik3.isSelected()){
            MINUM = "Messy Ice and Very Black Coffe";
        } else if (mimik1.isSelected()){
            MINUM = "Freezy Float";
        } else if (mimik2.isSelected()){
            MINUM = "Messy Ice";
        } else if (mimik3.isSelected()){
            MINUM = "Very Black Coffe";
        }
        
        int TTL_MAKAN = 0;
        if((maem1.isSelected() && maem2.isSelected()) && maem3.isSelected()){
            TTL_MAKAN = (40000+50000+60000)*jml_maem;
        } else if(maem1.isSelected() && maem2.isSelected()){
            TTL_MAKAN = (40000+50000)*jml_maem;
        } else if(maem1.isSelected() && maem3.isSelected()){
            TTL_MAKAN = (40000+60000)*jml_maem;
        } else if(maem2.isSelected() && maem3.isSelected()){
            TTL_MAKAN = (50000+60000)*jml_maem;
        } else if(maem1.isSelected()){
            TTL_MAKAN = 40000*jml_maem;
        } else if(maem2.isSelected()){
            TTL_MAKAN = 50000*jml_maem;
        } else if(maem3.isSelected()){
            TTL_MAKAN = 60000*jml_maem;
        }
        
        int TTL_MINUM = 0;
        if((mimik1.isSelected() && mimik2.isSelected()) && mimik3.isSelected()){
            TTL_MINUM = (20000+15000+10000)*jml_mimik;
        } else if(mimik1.isSelected() && mimik2.isSelected()){
            TTL_MINUM = (20000+15000)*jml_mimik;
        } else if(mimik1.isSelected() && mimik3.isSelected()){
            TTL_MINUM = (20000+10000)*jml_mimik;
        } else if(mimik2.isSelected() && mimik3.isSelected()){
            TTL_MINUM = (15000+10000)*jml_mimik;
        } else if(mimik1.isSelected()){
            TTL_MINUM = 20000*jml_mimik;
        } else if(mimik2.isSelected()){
            TTL_MINUM = 15000*jml_mimik;
        } else if(mimik3.isSelected()){
            TTL_MINUM = 10000*jml_mimik;
        }
        
        int TTL_POKOK = TTL_MAKAN + TTL_MINUM;
        int bagi = TTL_POKOK*(2/10);
        int TOTAL = 0;
        if (TTL_POKOK > 200000){
            TOTAL = TTL_POKOK - bagi;
        } else {
            TOTAL = TTL_POKOK;
        }
        
        int KEMBALI = yar - TOTAL;
        int KEBALIK = TOTAL - yar;
        String marah="";
        if(yar < TOTAL){
            marah="Anda berhutang "+KEBALIK+" harap lunasi segera";
        } else if (yar > TOTAL) {
            marah="Uang anda lebih "+KEMBALI+" semoga anda menggunakan uang anda di resto kami lagi";
        } else {
            marah="Uang anda pas jadi anda tidak perlu meminta uang kembalian kepada kami";
        }
        
        JOptionPane.showMessageDialog(null, "------------------- INI STRUK KEKINIAN --------------------\n\n\n"
                +"Makanan     : "+MAKAN+"\n"
                +"Minuman     : "+MINUM+"\n"
                +"Total Bayar : "+TOTAL+"\n"
                +"Uang Anda   : "+yar+"\n"
                +"Kembalian   : "+KEMBALI+"\n\n\n"
                +marah+"\n"
                +"Terima Kasih telah membeli dari resto kami\n","KHOFI PIZZA",1);
    }//GEN-LAST:event_printActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton del;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField maem;
    private javax.swing.JCheckBox maem1;
    private javax.swing.JCheckBox maem2;
    private javax.swing.JCheckBox maem3;
    private javax.swing.JTextField mimik;
    private javax.swing.JCheckBox mimik1;
    private javax.swing.JCheckBox mimik2;
    private javax.swing.JCheckBox mimik3;
    private javax.swing.JTextField nama;
    private javax.swing.JButton print;
    private javax.swing.JRadioButton s1;
    private javax.swing.JRadioButton s2;
    private javax.swing.JButton save;
    private javax.swing.JButton show;
    private javax.swing.JTextField tgl;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"Tanggal","NamaKasir","Shift","Makanan","JmlMakan","Minuman","JmlMinum","TotalHarga","UangBayar","UangKembali"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM penjualan";
        ResultSet rs = KoneksiDB.executeQuery(SQL);

        try{
            while(rs.next()){
                String Tanggal = rs.getString(0);
                String NamaKasir = rs.getString(1);
                String ES = "";
                if ("Pagi".equals(rs.getString(2))){
                    ES = "Pagi";
                } else {
                    ES = "Malam";
                }
                String Makanan = rs.getString(3);
                String JmlMakan = rs.getString(4);
                String Minuman = rs.getString(5);
                String JmlMinum = rs.getString(6);
                String TotalHarga = rs.getString(7);
                String UangBayar = rs.getString(8);
                String UangKembali = rs.getString(9);
                String data[] = {"Tanggal","NamaKasir","Shift","Makanan","JmlMakan","Minuman","JmlMinum","TotalHarga","UangBayar","UangKembali"};
                dtm.addRow(data);
            }
        } catch(SQLException ex){
            Logger.getLogger(kasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}

